name: qr_flutter
description: >
  QR.Flutter is a Flutter library for simple and fast QR code rendering via a
  Widget or custom painter.
version: 2.1.0+55
author: Luke Freeman <freeman.luke@gmail.com>
homepage: https://github.com/lukef/qr.flutter

environment:
  sdk: '>=2.1.0 <3.0.0'
  flutter: '>=1.2.0'

dependencies:
  flutter_web: any
  qr: ^1.1.0

dev_dependencies:
  flutter_web_test: any
  test: ^1.3.4

flutter:
  uses-material-design: false

dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui
  flutter_web_test:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_test
